"use client";
import{useState}from"react";
const templates={students:"admissionNumber,firstName,lastName,rollNumber,username,password,email,phone\nADM001,Arjun,Kumar,1,arjun001,ChangeMe123!,arjun@example.com,9876543210\n",teachers:"employeeId,name,username,password,email,phone,departmentId\nT001,Suresh Kumar,suresh001,ChangeMe123!,suresh@example.com,9876543210,"};
export default function ImportPage(){
 const[type,setType]=useState<"students"|"teachers">("students"),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(""),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false);
 async function choose(f:File|null){setFile(f);setResult(null);if(f)setPreview((await f.text()).split(/\r?\n/).slice(0,6).join("\n"));else setPreview("")}
 async function upload(){if(!file)return;setBusy(true);try{const r=await fetch("/api/import/"+type,{method:"POST",headers:{"content-type":"text/csv"},body:await file.text()});setResult(await r.json())}finally{setBusy(false)}}
 function downloadTemplate(){const blob=new Blob([templates[type]],{type:"text/csv"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=type+"-template.csv";a.click();URL.revokeObjectURL(url)}
 return <main className="p-5 pb-24 md:p-8"><div className="mx-auto max-w-4xl"><h1 className="text-4xl font-black">Bulk import</h1><p className="mt-2 text-slate-400">Validated transactional CSV import. A failed row prevents the batch from being committed.</p>
 <div className="card mt-6 p-6"><div className="grid gap-3 md:grid-cols-2"><select className="input" value={type} onChange={e=>{setType(e.target.value as any);setFile(null);setPreview("");setResult(null)}}><option value="students">Students</option><option value="teachers">Teachers</option></select><button className="btn" type="button" onClick={downloadTemplate}>DOWNLOAD {type.toUpperCase()} TEMPLATE</button></div>
 <input className="input mt-3" type="file" accept=".csv,text/csv" onChange={e=>choose(e.target.files?.[0]||null)}/><p className="mt-3 text-sm text-slate-400">{type==="students"?"Required: admissionNumber, firstName, username. Optional: lastName, rollNumber, password, email, phone.":"Required: employeeId, name, username. Optional: password, email, phone, departmentId."}</p>
 {preview&&<pre className="mt-4 max-h-48 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-300">{preview}</pre>}
 <button className="btn mt-4 bg-blue-600" disabled={!file||busy} onClick={upload}>{busy?"IMPORTING…":"VALIDATE & IMPORT"}</button></div>
 {result&&<div className="card mt-5 p-5"><p className={result.ok?"text-emerald-300":"text-amber-300"}>{result.ok?"Imported "+result.imported+" record(s).":"Import rejected: "+(result.error||"validation errors")}</p><pre className="mt-3 overflow-auto text-sm">{JSON.stringify(result,null,2)}</pre></div>}</div></main>}