"use client";
import{useEffect,useState}from"react";
export default function Calendar(){
 const[rows,setRows]=useState<any[]>([]),[years,setYears]=useState<any[]>([]),[year,setYear]=useState(""),[date,setDate]=useState(""),[name,setName]=useState(""),[type,setType]=useState("HOLIDAY"),[description,setDescription]=useState(""),[editing,setEditing]=useState<any>(null),[msg,setMsg]=useState("");
 async function load(){const r=await fetch("/api/calendar"+(year?"?academicYearId="+year:""));if(r.ok)setRows(await r.json())}
 useEffect(()=>{fetch("/api/academic-years").then(r=>r.json()).then(setYears);load()},[year]);
 async function save(e:any){e.preventDefault();setMsg("");const payload={academicYearId:year,date,name,type,description};const r=await fetch(editing?"/api/calendar/"+editing.id:"/api/calendar",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok){setMsg(d.error||"Could not save");return}reset();load()}
 function edit(x:any){setEditing(x);setYear(x.academicYearId);setDate(new Date(x.date).toISOString().slice(0,10));setName(x.name);setType(x.type);setDescription(x.description||"");window.scrollTo({top:0,behavior:"smooth"})}
 async function remove(id:string){if(!confirm("Delete this calendar day?"))return;const r=await fetch("/api/calendar/"+id,{method:"DELETE"});if(r.ok)load();else{const d=await r.json();setMsg(d.error||"Could not delete")}}
 function reset(){setEditing(null);setName("");setDate("");setDescription("");setType("HOLIDAY");setMsg("")}
 return <main className="p-5 pb-24 md:p-8"><div className="mx-auto max-w-6xl"><h1 className="text-4xl font-black">Academic calendar</h1><p className="mt-2 text-slate-400">Working days, holidays, exams and events.</p>
 <form onSubmit={save} className="card mt-6 grid gap-3 p-5 md:grid-cols-5"><select required className="input" value={year} onChange={e=>setYear(e.target.value)}><option value="">Academic year</option>{years.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input required className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/><input required className="input" placeholder="Name" value={name} onChange={e=>setName(e.target.value)}/><select className="input" value={type} onChange={e=>setType(e.target.value)}><option>HOLIDAY</option><option>WORKING</option><option>EXAM</option><option>EVENT</option></select><div className="flex gap-2"><button className="btn flex-1 bg-blue-600" type="submit">{editing?"UPDATE":"ADD DAY"}</button>{editing&&<button className="btn" type="button" onClick={reset}>CANCEL</button>}</div><input className="input md:col-span-5" placeholder="Description (optional)" value={description} onChange={e=>setDescription(e.target.value)}/></form>
 {msg&&<p className="mt-3 text-sm text-amber-300">{msg}</p>}
 <div className="card mt-6 overflow-auto p-5"><table className="w-full min-w-[650px] text-left"><thead><tr><th>Date</th><th>Name</th><th>Type</th><th>Description</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr className="border-t border-slate-800" key={x.id}><td className="py-3">{new Date(x.date).toLocaleDateString("en-IN")}</td><td>{x.name}</td><td>{x.type}</td><td>{x.description||"—"}</td><td><div className="flex gap-2"><button className="btn" onClick={()=>edit(x)}>Edit</button><button className="btn bg-red-700" onClick={()=>remove(x.id)}>Delete</button></div></td></tr>)}</tbody></table>{!rows.length&&<p className="py-8 text-center text-slate-500">No calendar days found.</p>}</div>
 </div></main>}